#------------------------------------------------------------------------------#
# FleCSI Gitlab CI: Main
#------------------------------------------------------------------------------#

stages:
  - Canary
  - Environment
  - Build + Unit Tests
  - Tutorial
  - Final

variables:
  COLOR_BLUE: '\033[1;34m'
  COLOR_GREEN: '\033[0;32m'
  COLOR_MAGENTA: '\033[1;35m'
  COLOR_PLAIN: '\033[0m'

include: .gitlab/environments.yml

#------------------------------------------------------------------------------#
# Formatting target.
#
# The selected image must have the required clang-format version
# installed during image creation in the 'gitlab-ci' branch.
#------------------------------------------------------------------------------#

format:diff:
  extends: .diff_format_template
  dependencies: []
  variables:
    REGISTRY: gitlab.lanl.gov:5050/laristra/flecsi
    IMAGE: util-fedora-30
    FORMAT_VERSION: 8.0.0
  allow_failure: true

format:check:
  extends: .check_format_template
  dependencies:
    - format:diff
  variables:
    REGISTRY: gitlab.lanl.gov:5050/laristra/flecsi
    IMAGE: util-fedora-30

#------------------------------------------------------------------------------#
# Build and unit tests for default settings.
#
# Image: CentOS 7.8
#------------------------------------------------------------------------------#

mpich-defaults:
  extends: .defaults_build_template
  dependencies:
    - mpich
  variables:
    ENVIRONMENT: devel
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/laristra/flecsi
    IMAGE: centos-7.8

#------------------------------------------------------------------------------#
# Build and unit tests for Legion runtime with MPICH provider,
# and GNU compiler toolchain.
#
# Image: CentOS 7.8
#------------------------------------------------------------------------------#

mpich-legion-gnu:
  extends: .build_template
  dependencies:
    - mpich
  variables:
    ENVIRONMENT: devel
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/laristra/flecsi
    IMAGE: centos-7.8
    BUILD_TYPE: debug
    RUNTIME: legion
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror -Wno-parentheses
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}

mpich-legion-gnu:release:
  extends: .build_template
  dependencies:
    - mpich:release
  variables:
    ENVIRONMENT: devel
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/laristra/flecsi
    IMAGE: centos-7.8
    BUILD_TYPE: release
    RUNTIME: legion
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror -Wno-parentheses
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}

#------------------------------------------------------------------------------#
# Build and unit tests for MPI runtime with MPICH provider,
# and GNU compiler toolchain.
#
# Image: CentOS 7.8
#------------------------------------------------------------------------------#

mpich-mpi-gnu:
  extends: .build_template
  dependencies:
    - mpich
  variables:
    ENVIRONMENT: devel
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/laristra/flecsi
    IMAGE: centos-7.8
    BUILD_TYPE: debug
    RUNTIME: mpi
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror -Wno-parentheses
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}

mpich-mpi-gnu:release:
  extends: .build_template
  dependencies:
    - mpich:release
  variables:
    ENVIRONMENT: devel
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/laristra/flecsi
    IMAGE: centos-7.8
    BUILD_TYPE: release
    RUNTIME: mpi
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror -Wno-parentheses
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}

#------------------------------------------------------------------------------#
# Tutorial tests for Legion runtime with MPICH provider,
# and GNU compiler toolchain.
#
# Image: CentOS 7.8
#------------------------------------------------------------------------------#

tutorial:legion:
  extends: .tutorial_template
  dependencies:
    - mpich-legion-gnu:release
  variables:
    ENVIRONMENT: devel
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/laristra/flecsi
    IMAGE: centos-7.8
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror -Wno-parentheses
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}

#------------------------------------------------------------------------------#
# Build and unit tests for Legion runtime with OpenMPI provider,
# and GNU compiler toolchain.
#
# Image: CentOS 7.8
#------------------------------------------------------------------------------#

openmpi-legion-gnu:
  extends: .build_template
  dependencies:
    - openmpi
  variables:
    ENVIRONMENT: devel
    MPI_PROVIDER: openmpi
    REGISTRY: gitlab.lanl.gov:5050/laristra/flecsi
    IMAGE: centos-7.8
    BUILD_TYPE: debug
    RUNTIME: legion
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror -Wno-parentheses
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}

openmpi-legion-gnu:release:
  extends: .build_template
  dependencies:
    - openmpi:release
  variables:
    ENVIRONMENT: devel
    MPI_PROVIDER: openmpi
    REGISTRY: gitlab.lanl.gov:5050/laristra/flecsi
    IMAGE: centos-7.8
    BUILD_TYPE: release
    RUNTIME: legion
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror -Wno-parentheses
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}

#------------------------------------------------------------------------------#
# Build and unit tests for MPI runtime with OpenMPI provider,
# and GNU compiler toolchain.
#
# Image: CentOS 7.8
#------------------------------------------------------------------------------#

openmpi-mpi-gnu:
  extends: .build_template
  dependencies:
    - openmpi
  variables:
    ENVIRONMENT: devel
    MPI_PROVIDER: openmpi
    REGISTRY: gitlab.lanl.gov:5050/laristra/flecsi
    IMAGE: centos-7.8
    BUILD_TYPE: debug
    RUNTIME: mpi
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror -Wno-parentheses
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}

openmpi-mpi-gnu:release:
  extends: .build_template
  dependencies:
    - openmpi:release
  variables:
    ENVIRONMENT: devel
    MPI_PROVIDER: openmpi
    REGISTRY: gitlab.lanl.gov:5050/laristra/flecsi
    IMAGE: centos-7.8
    BUILD_TYPE: release
    RUNTIME: mpi
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror -Wno-parentheses
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}

#------------------------------------------------------------------------------#
# Build and unit tests for Legion runtime with MPICH provider,
# and Clang compiler toolchain.
#
# Image: CentOS 7.8
#------------------------------------------------------------------------------#

mpich-legion-clang:
  extends: .build_template
  dependencies:
    - mpich-clang
  variables:
    ENVIRONMENT: devel
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/laristra/flecsi
    IMAGE: clearlinux
    BUILD_TYPE: debug
    RUNTIME: legion
    CXX_COMPILER: clang++
    CXX_FLAGS: -fcolor-diagnostics -Wall -W -Werror -Wno-parentheses
    C_COMPILER: clang
    C_FLAGS: ${CXX_FLAGS}

#------------------------------------------------------------------------------#
# Build and unit tests for Legion runtime with MPICH provider,
# Clang compiler toolchain and kokkos serial
#
# Image: CentOS 7.8
#------------------------------------------------------------------------------#

mpich-legion-clang-kokkos-serial:
  extends: .build_template
  dependencies:
    - mpich-clang
  variables:
    ENVIRONMENT: devel
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/laristra/flecsi
    IMAGE: clearlinux
    BUILD_TYPE: debug
    RUNTIME: legion
    CXX_COMPILER: clang++
    CXX_FLAGS: -fcolor-diagnostics -Wall -W -Werror -Wno-parentheses
    C_COMPILER: clang
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: -DENABLE_KOKKOS=ON

#------------------------------------------------------------------------------#
# Build and unit tests for MPI runtime with MPICH provider,
# and Clang compiler toolchain.
#
# Image: CentOS 7.8
#------------------------------------------------------------------------------#

mpich-mpi-clang:
  extends: .build_template
  dependencies:
    - mpich-clang
  variables:
    ENVIRONMENT: devel
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/laristra/flecsi
    IMAGE: clearlinux
    BUILD_TYPE: debug
    RUNTIME: mpi
    CXX_COMPILER: clang++
    CXX_FLAGS: -fcolor-diagnostics -Wall -W -Werror -Wno-parentheses
    C_COMPILER: clang
    C_FLAGS: ${CXX_FLAGS}

#------------------------------------------------------------------------------#
# Build and unit tests for MPI runtime with OpenMPI provider,
# and Clang compiler toolchain.
#
# Image: CentOS 7.8
#------------------------------------------------------------------------------#

openmpi-mpi-clang:
  extends: .build_template
  dependencies:
    - openmpi-clang
  variables:
    ENVIRONMENT: devel
    MPI_PROVIDER: openmpi
    REGISTRY: gitlab.lanl.gov:5050/laristra/flecsi
    IMAGE: clearlinux
    BUILD_TYPE: debug
    RUNTIME: mpi
    CXX_COMPILER: clang++
    CXX_FLAGS: -fcolor-diagnostics -Wall -W -Werror -Wno-parentheses
    C_COMPILER: clang
    C_FLAGS: ${CXX_FLAGS}
