#------------------------------------------------------------------------------#
# FleCSI Gitlab CI: Main
#------------------------------------------------------------------------------#

stages:
  - Canary
  - Environment
  - Build + Unit Tests
  - Standalone
  - Final

variables:
  COLOR_BLUE: '\033[1;34m'
  COLOR_GREEN: '\033[0;32m'
  COLOR_MAGENTA: '\033[1;35m'
  COLOR_PLAIN: '\033[0m'

include: .gitlab/environments.yml

#------------------------------------------------------------------------------#
# Formatting target.
#
# The selected image must have the required clang-format version
# installed during image creation in the 'gitlab-ci' branch.
#------------------------------------------------------------------------------#

format:diff:
  extends: .diff_format_template
  dependencies: []
  only:
    - merge_requests
  variables:
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: util-fedora-30
    FORMAT_VERSION: 8.0.0
  allow_failure: true

format:check:
  extends: .check_format_template
  needs:
    - job: format:diff
      artifacts: true
    - job: tutorial:legion
    - job: poisson:legion
  only:
    - merge_requests
  variables:
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: util-fedora-30

#------------------------------------------------------------------------------#
# Build and unit tests for default settings.
#------------------------------------------------------------------------------#

mpich-defaults:
  extends: .defaults_build_template
  needs:
    ["mpich"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: rockylinux

#------------------------------------------------------------------------------#
# Build and unit tests for Legion backend with MPICH provider,
# and GNU compiler toolchain.
#------------------------------------------------------------------------------#

mpich-legion-gnu:
  extends: .build_template
  needs:
    ["mpich-debug"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: rockylinux
    BUILD_TYPE: Debug
    BACKEND: legion
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: -DENABLE_FLOG=ON -DENABLE_HDF5=ON -DENABLE_KOKKOS=ON

mpich-legion-gnu:release:
  extends: .build_template
  needs:
    ["mpich"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: rockylinux
    BUILD_TYPE: Release
    BACKEND: legion
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: -DENABLE_FLOG=ON -DENABLE_HDF5=ON -DENABLE_KOKKOS=ON

#------------------------------------------------------------------------------#
# Build and unit tests for MPI backend with MPICH provider,
# and GNU compiler toolchain.
#------------------------------------------------------------------------------#

mpich-mpi-gnu:
  extends: .build_template
  needs:
    ["mpich-debug"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: rockylinux
    BUILD_TYPE: Debug
    BACKEND: mpi
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: -DENABLE_FLOG=ON -DENABLE_HDF5=ON

mpich-mpi-gnu:release:
  extends: .build_template
  needs:
    ["mpich"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: rockylinux
    BUILD_TYPE: Release
    BACKEND: mpi
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: -DENABLE_FLOG=ON -DENABLE_HDF5=ON

#------------------------------------------------------------------------------#
# Tutorial tests for Legion backend with MPICH provider,
# and GNU compiler toolchain.
#------------------------------------------------------------------------------#

tutorial:legion:
  extends: .standalone_template
  needs:
    ["mpich-legion-gnu"]
  only:
    - merge_requests
  variables:
    LABEL: tutorial
    STDIR: tutorial
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: rockylinux
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror -Wno-parentheses
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}

poisson:legion:
  extends: .standalone_template
  needs:
    ["mpich-legion-gnu"]
  only:
    - merge_requests
  variables:
    LABEL: standalone
    STDIR: tutorial/standalone/poisson
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: rockylinux
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}

#------------------------------------------------------------------------------#
# Build and unit tests for Legion backend with OpenMPI provider,
# and GNU compiler toolchain.
#------------------------------------------------------------------------------#

openmpi-legion-gnu:
  extends: .build_template
  needs:
    ["openmpi-debug"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: openmpi
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: rockylinux
    BUILD_TYPE: Debug
    BACKEND: legion
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: -DENABLE_FLOG=ON -DENABLE_HDF5=ON

openmpi-legion-gnu:release:
  extends: .build_template
  needs:
    ["openmpi"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: openmpi
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: rockylinux
    BUILD_TYPE: Release
    BACKEND: legion
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: -DENABLE_FLOG=ON -DENABLE_HDF5=ON

#------------------------------------------------------------------------------#
# Build and unit tests for MPI backend with OpenMPI provider,
# and GNU compiler toolchain.
#------------------------------------------------------------------------------#

openmpi-mpi-gnu:
  extends: .build_template
  needs:
    ["openmpi-debug"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: openmpi
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: rockylinux
    BUILD_TYPE: Debug
    BACKEND: mpi
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: -DENABLE_FLOG=ON -DENABLE_HDF5=ON

openmpi-mpi-gnu:release:
  extends: .build_template
  needs:
    ["openmpi"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: openmpi
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: rockylinux
    BUILD_TYPE: Release
    BACKEND: mpi
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: -DENABLE_FLOG=ON -DENABLE_HDF5=ON

#------------------------------------------------------------------------------#
# Build and unit tests for Legion backend with MPICH provider,
# and Clang compiler toolchain.
#------------------------------------------------------------------------------#

mpich-legion-clang:
  extends: .build_template
  needs:
    ["mpich-clang-debug"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: fedora-34
    BUILD_TYPE: Debug
    BACKEND: legion
    CXX_COMPILER: clang++
    CXX_FLAGS: -fcolor-diagnostics -Wall -W -Werror
    C_COMPILER: clang
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: -DENABLE_FLOG=ON -DENABLE_HDF5=ON -DENABLE_KOKKOS=ON

#------------------------------------------------------------------------------#
# Build and unit tests for MPI backend with MPICH provider,
# and Clang compiler toolchain.
#------------------------------------------------------------------------------#

mpich-mpi-clang:
  extends: .build_template
  needs:
    ["mpich-clang-debug"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: fedora-34
    BUILD_TYPE: Debug
    BACKEND: mpi
    CXX_COMPILER: clang++
    CXX_FLAGS: -fcolor-diagnostics -Wall -W -Werror
    C_COMPILER: clang
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: -DENABLE_FLOG=ON -DENABLE_HDF5=ON

#------------------------------------------------------------------------------#
# Build and unit tests for MPI backend with OpenMPI provider,
# and Clang compiler toolchain.
#------------------------------------------------------------------------------#

openmpi-mpi-clang:
  extends: .build_template
  needs:
    ["openmpi-clang-debug"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: openmpi
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: fedora-34
    BUILD_TYPE: Debug
    BACKEND: mpi
    CXX_COMPILER: clang++
    CXX_FLAGS: -fcolor-diagnostics -Wall -W -Werror
    C_COMPILER: clang
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: -DENABLE_FLOG=ON -DENABLE_HDF5=ON
