#------------------------------------------------------------------------------#
# FleCSI Gitlab CI: Environments
#------------------------------------------------------------------------------#

include: .gitlab/templates.yml

mpich:
  extends: .env_template
  dependencies: []
  variables:
    ENVIRONMENT: devel
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: centos-8
    VERSION: flecsi@devel
    VARIANTS: +hdf5 +kokkos

mpich-clang:
  extends: .env_template
  dependencies: []
  variables:
    ENVIRONMENT: devel
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: clearlinux
    VERSION: flecsi@devel
    VARIANTS: +hdf5 +kokkos

openmpi:
  extends: .env_template
  dependencies: []
  variables:
    ENVIRONMENT: devel
    MPI_PROVIDER: openmpi
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: centos-8
    VERSION: flecsi@devel
    VARIANTS: +hdf5

openmpi-clang:
  extends: .env_template
  dependencies: []
  variables:
    ENVIRONMENT: devel
    MPI_PROVIDER: openmpi
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: clearlinux
    VERSION: flecsi@devel
    VARIANTS: +hdf5
